Repository WordPress/spain-handbook, pull requests merged in 2023-11, with the labels that each got.

#145 Manual de markdown
  manuales/markdown/index.md
Labels: [Nivel] Principiantes, [Contenido] Nuevo, [Prioridad] Alto, [Proyecto] Contributor Day, [Equipo] Meta

#146 Página principal
  index.md
Labels: [Nivel] Principiantes, [Contenido] Nuevo, [Prioridad] Alto, [Proyecto] Contributor Day

#147 Añadir sección de manuales
  manuales/index.md
Labels: [Nivel] Principiantes, [Contenido] Nuevo, [Prioridad] Media, [Proyecto] Contributor Day

#148 cuentas WordPress
  assets/manuales-wordpress-crear-1.png
  assets/manuales-wordpress-crear-2.png
  assets/manuales-wordpress-crear-3.png
  assets/manuales-wordpress-recuperar-1.png
  assets/manuales-wordpress-sincronizar-1.png
  assets/manuales-wordpress-sincronizar-2.png
  assets/manuales-wordpress-sincronizar-3.png
  assets/manuales-wordpress-sincronizar-4.png
  manuales/wordpress/crear.md
  manuales/wordpress/index.md
  manuales/wordpress/recuperar.md
  manuales/wordpress/sincronizar.md
Labels: [Nivel] Principiantes, [Contenido] Nuevo, [Contenido] Actualización, [Prioridad] Alto, [Proyecto] Contributor Day

#150 Páginas de Equipo
  accesibilidad/index.md
  bin/handbook-manifest.json
  comunidad/index.md
  diseno/index.md
  marketing/index.md
  soporte/index.md
  traduccion/index.md
  traducciones/index.md
  tv/index.md
Labels: [Prioridad] Baja, [Proyecto]

#153 agenda de equipo
  bin/handbook-manifest.json
  equipo/agenda.md
Labels: [Proyecto]

#158 Creado el archivo principal del manual de Github y otros archivos.
  assets/manuales-wordpress-crear-cuenta-github.png
  bin/handbook-manifest.json
  manuales/github/crear.md
  manuales/github/cuenta.md
  manuales/github/index.md
  manuales/github/version-base.md
Labels: [Contenido] Nuevo, [Prioridad] Media, [Nivel] Avanzados, [Proyecto] Contributor Day
