Repository WordPress/spain-handbook, pull requests merged in 2024-10, with the labels that each got.

#365 Manifest al día y actualizaciones de arquitectura
  bin/handbook-manifest.json
  bin/wphandbook-manifest.json
  hosting/servidor/index.md
Labels: [Prioridad] Alto, [Proyecto]

#358 Página del Equipo de Sostenibilidad
  bin/handbook-manifest.json
  bin/wphandbook-manifest.json
  sostenibilidad/index.md
Labels: [Contenido] Nuevo, Publicar

#366 Manual de Eventos
  eventos/comunicacion/index.md
  eventos/empezar/index.md
  eventos/inclusion/index.md
  eventos/index.md
  eventos/organizadores/index.md
  eventos/patrocinadores/index.md
  eventos/presupuesto/index.md
  eventos/sostenibilidad/index.md
Labels: [Nivel] Principiantes, [Contenido] Nuevo, [Prioridad] Alto, [Proyecto], [Proyecto] Contributor Day

#370 Actualización página de Equipo de Documentación
  bin/handbook-manifest.json
  bin/wphandbook-manifest.json
  documentacion/index.md
Labels: [Nivel] Principiantes, [Contenido] Nuevo, [Prioridad] Baja, [Proyecto] Contributor Day, [Equipo] Documentación, Publicar

#362 Eventos inclusivos
  bin/handbook-manifest.json
  bin/wphandbook-manifest.json
  comunidad/wordcamp/index.md
  eventos/inclusion/index.md
Labels: [Contenido] Nuevo, Publicar

#356 Manual de eventos sostenibles
  bin/handbook-manifest.json
  bin/wphandbook-manifest.json
  eventos/sostenibilidad/asistentes/index.md
  eventos/sostenibilidad/catering/index.md
  eventos/sostenibilidad/contenido/index.md
  eventos/sostenibilidad/index.md
  eventos/sostenibilidad/inspiracion/index.md
  eventos/sostenibilidad/lugar/index.md
  eventos/sostenibilidad/marketing/index.md
  eventos/sostenibilidad/patrocinadores/index.md
  eventos/sostenibilidad/regalos/index.md
  eventos/sostenibilidad/ubicacion/index.md
  eventos/sostenibilidad/viajes/index.md
Labels: [Contenido] Nuevo, Publicar
